### ISSUE TITLE
Work on the Wiki

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#5]
## To-do list for release
- [x] Need to finish documenting things like transactions etc.
- [x] Need to provide examples of how to use the API.
- [x] Add updating instructions to the installation page.

## To-do list for the future
- [x] Explain the internal design and workings of the library, e.g. accounts, currencies, and so on.

**Comment by MrIvanPlays** [comment]
Update settings.yml and messages.yml pages to the latest changes

**Comment by lokka30** [comment]
Done a bunch of work documenting the [Economy API](https://github.com/lokka30/Treasury/wiki/Treasury's-Economy-API). Will work on updating those two pages now, thanks for letting me know.

**Comment by lokka30** [comment]
Updated settings.yml and messages.yml pages.

**Comment by MrNemo64** [comment]
Won't you mention the command to download the jar on the Installing Treasury wiki page, Updating Treasury section?

**Comment by MrIvanPlays** [comment]
> Won't you mention the command to download the jar on the Installing Treasury wiki page, Updating Treasury section?

Ye we need to update those too and also update the commands and permissions section.

**Comment by MrIvanPlays** [comment]
commands and permissions have been updated, also added a clarification in `Compiling Treasury` to ignore the jar ending with `-source`

**Comment by lokka30** [comment]
Thanks guys!

**Comment by MrIvanPlays** [comment]
I am very bad at really writing stuff in english so I'm leaving wiki up to you @lokka30 

Looking from the TODO's it can probably be finished in a day or two, no?

**Comment by lokka30** [comment]
> I am very bad at really writing stuff in english so I'm leaving wiki up to you @lokka30
> 
> Looking from the TODO's it can probably be finished in a day or two, no?

I'm pretty quick at this so it should be done by then. :)

Once I finish the [Subscriptions](https://github.com/lokka30/Treasury/wiki/Treasury's-Economy-API#subscriptions) section of the page, I'll need someone to read over it once just to make sure I haven't said anything incorrect in my explanation of that system.

**Comment by lokka30** [comment]
Done!! Interested in getting anyone to review it, especially over the subscriptions section, just to make sure I haven't screwed anything up. Tagging users who may be interested - this is not a request, only a 'if you're comfortable to do it, it would be much appreciated': @MrIvanPlays @Jikoo @MrNemo64
Will close this issue, but will re-open it if there is anything substantial wrong with the page that I can't fix in a jiffy.

**Comment by lokka30** [comment]
I would also like to add, that we probably need to re-build the javadocs. I think this will be the last time we need to do so before release. Except, I've noticed an error with the javadocs [here](https://jd.mrivanplays.com/treasury/api/me/lokka30/treasury/api/economy/response/EconomySubscriber.html#asFuture-java.util.function.Consumer-), and I'm unsure what it's caused by, perhaps it didn't like the combination of `<pre>` and `{@code`.
